//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalaxyLotto.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DBOptions;Persist Security Info" +
            "=True;User ID=ellischu;Password=Eunice168")]
        public string DBOptionsCS {
            get {
                return ((string)(this["DBOptionsCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DBMethod;Persist Security Info=" +
            "True;User ID=ellischu;Password=Eunice168")]
        public string DBMethodCS {
            get {
                return ((string)(this["DBMethodCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DB539Data;Persist Security Info" +
            "=True;User ID=ellischu;Password=Eunice168")]
        public string DB539DataCS {
            get {
                return ((string)(this["DB539DataCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DBLottoBig;Persist Security Inf" +
            "o=True;User ID=ellischu;Password=Eunice168")]
        public string DBBigDataCS {
            get {
                return ((string)(this["DBBigDataCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DBLottoDafu;Persist Security In" +
            "fo=True;User ID=ellischu;Password=Eunice168")]
        public string DBDafuDataCS {
            get {
                return ((string)(this["DBDafuDataCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DBLottoWeli;Persist Security In" +
            "fo=True;User ID=ellischu;Password=Eunice168")]
        public string DBWeliDataCS {
            get {
                return ((string)(this["DBWeliDataCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DBLottoSix;Persist Security Inf" +
            "o=True;User ID=ellischu;Password=Eunice168")]
        public string DBSixDataCS {
            get {
                return ((string)(this["DBSixDataCS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOME001\\SQLEXPRESS;Initial Catalog=GL_DB539Freq;Persist Security Info" +
            "=True;User ID=ellischu;Password=Eunice168")]
        public string DB539FreqCS {
            get {
                return ((string)(this["DB539FreqCS"]));
            }
        }
    }
}
